classDiagram

    class Estudiante {
        -id: int
        -nombre: string
        -email: string
        -idCarrera: string
        +registrar(): void
        +editarPerfil(): void
        +consultarCursosDisponibles(): List<Curso>
        +consultarCursosMatriculados(): List<Curso>
    }
 
    class Curso {
        -codigo: string
        -nombre: string
        -creditos: int
        +matricular(): void
        +retirar(): void
    }
  
    class Periodo {
        -año: int
        -nombre: string
        -activo: booleano
        +iniciarPeriodo(): void
        +finalizarPeriodo(): void
    }

    class Profesor {
        -idProfesor: int
        -nombre: string
        -correo: string
        +asignarCurso(): void
        +consultarCursos(): List<Curso>
    }

    class Matricula {
        -idMatricula
        -idEstudiante
        -idGrupo: int
        -fecha: date
    }

    class Grupo {
        -id_grupo: int
        -idCurso: int
        -idProfesor: int?
        -idPeriodo: int
        -capacidad: int
        -numero_grupo: int 
        -horario: string
        +agregarEstudiante(): void
        +consultarEstudiantes(): List<Estudiante>
    }


Grupo "1" -- "1" Curso : ofrece
Grupo "1" -- "1" Profesor : impartido por
Grupo "1" -- "1" Periodo : en
Estudiante "1" -- "1..*" Matricula : realiza
Matricula "1" -- "1" Grupo : de
